### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by roboticruler** [xerootg/cryze_v2#12]
I'm kind of new to this, and all of this looks overwhelming, is there any way you could post a detailed tutorial?

**Comment by xerootg** [comment]
To be fair, this thing is complicated. I've got the benefit of working on it everyday for a month ;)

Keep in mind this will only run on an x86 machine right now (i.e. a traditional laptop/desktop) until I fix some issues in the android stack. Technically, you should be able to run it on windows if you get WSL setup to run redroid.

The most basic way to launch this thing is to actually start by setting up your os for redroid. That means getting a kernel that supports binder and ashmem or memfd (see the redroid docs at https://github.com/remote-android/redroid-doc). Then make sure docker and compose are installed. At this point, you've got the prereqs for this stack.

Clone this repo. Copy sample.env and name it .env, updating the values to your credentials.

You have two options at this point: host cryzev2 and frigate or just cryzev2. If you want frigate, replace docker-compose.yml with docker-compose.frigate.yml. there's one value in the yml for mediamtx if your not using frigate that needs to be set to your machine's network IP (this should be a stable/static IP).

Then, run `docker compose build` and then `docker compose up -d`if the build does not fail. The cryze webpage is on port 8080, cameras are published to mediamtx just like they are in docker-wyze-bridge - nicknames to lowercase and spaces are replaced with underscores. For example, a wyze camera named Street View would be at rtsp://[up of your docker machine]:8554/street_view

I'm not going to publish images of this until things are a bit more stable, I'm working on a significantly stripped down redroid container which *might* have docker implications that I don't have fully figured out yet.

**Comment by xerootg** [comment]
@roboticruler did you figure it out?
