### ISSUE TITLE
Getting a 400 Client Error on the Waze API

### ISSUE THREAD

**Issue by bhsuarez** [xerootg/cryze_v2#13]
`      2024-09-16 00:26:51,916 - wyze_sdk.service.base - INFO - requesting POST to https://auth-prod.api.wyze.com/api/user/login
warn: Cryze.API.Services.WyzeSdkService[0]
      Failed to login to Wyze API, not saving token
warn: Cryze.API.Services.WyzeSdkService[0]
      Failed to get supported cameras
      Python.Runtime.PythonException: 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/api/user/login
        File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 1024, in raise_for_status`

Seems the api container continues to restart because of this. Any ideas what to do? I've tried a new API key.

**Comment by xerootg** [comment]
That sure looks like what I remember happening when the user/pass/apikey/token weren't set in the API container. If you set the environment variable StoreConfiguration__LoadWyzeSupportedCamerasOnStartup=false on the API container, does it boot?
(Edited: false, not true. Default is true)

**Comment by xerootg** [comment]
@bhsuarez can you peek at your .env file and the one that @iamareuben just merged and see if this brings your API up?
