### ISSUE TITLE
connected but no stream

### ISSUE THREAD

**Issue by JoshuaSeidel** [xerootg/cryze_v2#14]
i connected to my OG camera. it shows it under the camera tab
![image](https://github.com/user-attachments/assets/15095e86-c6f6-4e90-97ea-80bafddb16af)

but the camera messages tab is empty. and there is nothing coming through the RTSP

do you have any ideas?

**Comment by JoshuaSeidel** [comment]
this is in android logs

```09-25 20:06:12.563 22899 22899 E LogcatWatchdog: cryze process not found```

mediamtx
```2024/09/25 19:49:48 INF [RTSP] [conn 172.18.0.2:42590] closed: no one is publishing to path 'live/pet_cam'```

**Comment by xerootg** [comment]
That tells me that the build failed/the install script partially ran. Thats no good! Can you connect to the android container with scrcpy?
Install scrcpy: https://github.com/Genymobile/scrcpy

See if the docker container has already added itself to your adb instance:
`adb devices`

if it hasn't:
`adb connect <ip to dockerhost>:5555`

and finally connect to android:
`scrcpy`

If the app is running, you should see something like:
![image](https://github.com/user-attachments/assets/dd16d726-efd8-42b5-9e72-51b44ec606db)

If its not running, check the app menu:
![image](https://github.com/user-attachments/assets/2eeed83e-1b45-4c63-b7a8-589514ab005f)

if its not installed:
`adb shell pm install --abi arm64-v8a -g --full /app/app.apk`

If it is installed, manually start it and if it crashes, it should show up in logcat as to why. sorry for the fire drill! This is a pretty young project in all reality.

**Comment by GerardArmstrong** [comment]
I have followed instructions above and can see the android app streaming using adb and scrcpy.

When I try to open the rtsp stream in VLC I get:

mediamtx_1           | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52152] opened
mediamtx_1           | 2024/09/27 06:34:15 INF [RTSP] [session 01f2f428] created by 172.18.0.1:52152
mediamtx_1           | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52152] closed: path has changed, was '/gw1', now is '/stream=0'
mediamtx_1           | 2024/09/27 06:34:15 INF [RTSP] [session 01f2f428] destroyed: not in use
mediamtx_1           | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52158] opened
mediamtx_1           | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52158] closed: EOF

**Comment by reubenmade** [comment]
I had the same issue as @JoshuaSeidel, and while trying to connect to ADB I was struggling.  I did a bit of reading on redroid, and found I needed to run some commands in my ubuntu docker host per the getting started guide at https://hub.docker.com/r/redroid/redroid

```
apt install linux-modules-extra-`uname -r`
modprobe binder_linux devices="binder,hwbinder,vndbinder"
```

Not sure if it's the same issue, but this has solved it for me - both allowed me to connect with ADB/scrcpy, and allowed the cryze app to actually run in the container.  Now have RTSP streams coming off my camera.

**Comment by GerardArmstrong** [comment]
> I have followed instructions above and can see the android app streaming using adb and scrcpy.
> 
> When I try to open the rtsp stream in VLC I get:
> 
> mediamtx_1 | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52152] opened mediamtx_1 | 2024/09/27 06:34:15 INF [RTSP] [session 01f2f428] created by 172.18.0.1:52152 mediamtx_1 | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52152] closed: path has changed, was '/gw1', now is '/stream=0' mediamtx_1 | 2024/09/27 06:34:15 INF [RTSP] [session 01f2f428] destroyed: not in use mediamtx_1 | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52158] opened mediamtx_1 | 2024/09/27 06:34:15 INF [RTSP] [conn 172.18.0.1:52158] closed: EOF

This is working now - was an issue with gstreamer1.0-libav not installed on my client.

**Comment by xerootg** [comment]
Not having binder will prevent Android from booting at its most rudimentary levels, so that makes sense. But I don't understand the connection to gstreamer or even if the original issue was solved.
